### ISSUE TITLE
Trouble with blog page and homepage - Mix up templates

### ISSUE THREAD

**Issue by marou-lia** [srikat/oxygen-theme-enabler#2]
Hi !
I thank you first for this plugin, very helpful for me.
I have a juste a problem with some templates

I have a wordpress website with my own theme working well, since years.

For now, I wan to add 1 page, that I want to build with Oxygen.

I installed your plugin.
I choose in the settings "Use theme for most pages but use Oxygen on the select views defined by the condition(s) in plugin file"
And I put in the plugin file the right conditions (give the ID of my new Oxy Page)

All is working very well :
- All my pages are using the page template (except the one I gave the ID)
- No problem with my 404
- My custom posts archive and single, and my single post are using my theme dedicated template
BUT
My homepage (which is a page) should use front-page.php... and it is now using page.php
My blog page (which is not my front page) should use home.php... and it is now using page.php

Can you help me to understand why the plugin is creating a mix up with my theme templates ? 

Thanks for reading !

**Comment by marou-lia** [comment]
Hi...
I answer my own issue.
Perhaps it will help other oxy-beginners like me !

So If you don't want to make a big mix up with your theme templates : 
When you are creating a template in Oxygen, at the question "where does this template apply ?" you just have NOT to choose "Catch all" or "Pages" , or anything else...

Easy !

**Comment by natewitty** [comment]
@marou-lia  Thank you for posting this solution. You definitely helped me. My blog pages weren't using the correct single.php template and I thought I was going to have to stop using Oxygen. This was what I needed to find. Thanks again.
