### ISSUE TITLE
Not working after Oxygen 3.7

### ISSUE THREAD

**Issue by AlkoKod** [srikat/oxygen-theme-enabler#6]
Hello, at first, thanks for nice plugin. It was working really good for me. 

Now I updated the site I am working on to Oxygen 3.7 and it looks like coditions for pages which should use the Oxygen templates are not working anymore. 

- Use theme for most pages but use Oxygen on the select views defined by the condition(s) in plugin file - not working

Can you help?

**Comment by srikat** [comment]
Just tested and it is working fine here.

Oxygen 3.7.1 and Twenty Twenty-One 1.2.

How can the problem be reproduced?

**Comment by AlkoKod** [comment]
Hello, try to use this settings: 

- Use theme for most pages but use Oxygen on the select views defined by the condition(s) in plugin file

Theme: Astra free

Used conditions:
return is_woocommerce();
return is_page( 'shop' );

**Comment by AlkoKod** [comment]
It was my mistake in PHP code. Sorry for disturbing. Set this to return (is_shop() || is_woocommerce() || is_product()); - works again.
